services:
      php_app:
        image: php:8.3-fpm
        volumes:
          - ./frontend:/var/www/html
      nginx_server:
        image: nginx:alpine
        ports:
          - "1234:80" # change the first port number to match your needs
        volumes:
          - ./frontend:/var/www/html
          - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        restart: always
